#!/usr/bin/env bash

source ./lib/user-menu
source ./lib/script-init-output
source ./lib/system-monitoring-menu
source ./lib/server-setup-menu
source ./lib/security-audit-menu

print_main() {
	local menu=(UserConfig Monitoring ServerSetup Security Exit\(q\))
	local i=1
	for  item in "${menu[@]}"; do
		echo "${i} : ${item}"
		((i ++))
	done
	printf '\n'
}

main_menu() {
	print_main
	while true; do
		read -p "Please choose: " choice
		printf '\n'
		case "$choice" in
			1) user_menu_actions ;;
			2) monitoring_menu ;;
			3) server_setup_menu ;;
			4) security_menu ;;
			q) exit 0 ;;
		esac
	done
}

start_menu
main_menu
