#!/usr/bin/env bash

source ../main
source ./script-logging-function

apps_to_install=('git' 'wget' 'htop' 'tcpdump' 'zip' 'tar' 'firewalld' 'tree' 'jq' 'sysstat' 'dnsutils')
declare -A dict_apps_to_install

print_server_setup() {
	printf '\n'
	local menu=(listAppsForInstall bulkInstallList installFromFile 'Exit(q)')
	local i=1
	for  item in "${menu[@]}"; do
		echo "${i} : ${item}"
		((i ++))
	done
	printf '\n'
}

server_setup_menu() {
	print_server_setup
	while true; do
		read -p "Please choose: " choice
		printf '\n'
		case "$choice" in
			1) list_apps_for_install ;;
			2) bulk_install ;;
			3) install_from_file ;;
			q) main_menu ;;
		esac
	done
}

list_apps_for_install(){
	for app in "${apps_to_install[@]}"; do
		echo "$app"
	done
	print_server_setup
}

bulk_install(){
	echo "Updating packages before installing apps..."
	echo "-----------------------------------------------"
	sleep 1
	apt-get update -y
	sleep 1
	echo "Installing from the default list of apps..."

	for app_to_install in "${apps_to_install[@]}"; do
		apt-get install -y "$app_to_install"
		if [ $? -eq 0 ]; then
			echo "$app_to_install installed."
			dict_apps_to_install["${app_to_install}"]="Installed"
		else
			echo "$app_to_install failed to install..."
			dict_apps_to_install["${app_to_install}"]="Not Installed"
		fi
	done

	echo "Successfully installed the following apps:"

	for check_app in "${!dict_apps_to_install[@]}"; do
		if [[ ${dict_apps_to_install["${check_app}"]} == "Installed" ]]; then
			echo "${check_app}"
		fi
	done

	echo "-----------------------------------------------"
	echo "Could not install the following apps:"
	for check_app in "${!dict_apps_to_install[@]}"; do
		if [[ ${dict_apps_to_install["${check_app}"]} == "Not Installed" ]]; then
			echo "${check_app}"
		fi
	done
	print_server_setup
}

install_from_file(){
	echo "CAUTION: Install file must be in the following format:"
	printf 'appname\n appname\n'
	echo "Note, it's just the package names each on a new line..."

	local file_path
	local app_count
	local answer
	
	app_count=0
	read -p "Please provide filepath: " filepath
	echo "Apps to be installed"
	echo "--------------------------------------"
	while read -r line; do
		(( app_count++ ))
		echo $line
	done < "${filepath}"
	
	sleep 1
	printf '\n'
	read -p "Please confirm you want to install these ${app_count} packages (y/n)" answer
	if [[ "${answer}" == "n" ]]; then
		echo "Exiting back to server menu..."
		print_server_setup
	else
		echo "Installing apps..."
		while read -r line; do
			echo "installing ${line}"
			apt-get install ${line} -y 			 
			if [ $? -eq 0 ] ; then
				echo "Successfully installed ${line}"
			else 
				echo "Could not install ${line}"
			fi
			echo "-------------------------------"
			sleep 1
		done < "${filepath}"
	fi
	print_server_setup
}
