#!/usr/bin/env bash

source ../main

monitoring_menu(){
	
	print_system
	while true; do
		read -p "Please choose: " schoice
		printf '\n'
		case "$schoice" in
			1) system_info_get ;;
			2) process_load_get ;;
			q) main_menu ;;
		esac
	done
}

print_system(){

	local sysMenuOptions=(getSystemHealth getTopProcesses endTopProcess 'Main menu (q)')
	local i=1	

	for item in "${sysMenuOptions[@]}"; do
		if [[ $item == "Exit" ]]; then
			echo "q: Exit"
		else
			echo "${i}: ${item}"
			(( i++ ))
		fi
	done
	printf '\n'
}

system_info_get(){
	
	local uptime_metric="$(uptime | cut -d , -f 1)"
	local load_metric="$(uptime | cut -d , -f 3-)"
	local os_kernel_info="$(cat /proc/version)"
	local cpu_metric="$(cat /proc/cpuinfo)"
	local mem_metric="$(cat /proc/meminfo)"


	echo "Checking uptime..."
	sleep 1
	printf '%s\n' "$uptime_metric"
	
	echo "--------------------------"
	
	echo "Checking Average load..."	
	sleep 1
	printf '%s\n' "$load_metric"

	echo "--------------------------"

	echo "Printing OS, Kernel, gcc info..."
	sleep 1
	printf '%s\n' "$os_kernel_info"

	echo "--------------------------"
	echo "Printing CPU info..."
	sleep 1
	printf '%s\n' "$cpu_metric"

	echo "--------------------------"
	echo "Printing Memory info..."
	sleep 1
	printf '%s\n' "$mem_metric"

	echo "--------------------------"
	echo "Going back to monitoring menu..."
	printf '\n'
	sleep 1
	monitoring_menu
}

process_load_get() {
	
	local psaux_cpu="$(ps aux --sort=-%cpu | head -n 6)"
	local psaux_mem="$(ps aux --sort=-%mem | head -n 6)"

	echo "Getting top 5 CPU-intensive processes..."
	sleep 1
	printf '%s\n\n' "$psaux_cpu"
	
	echo "Getting top 5 Memory-intensive processes..."
	sleep 1
	printf '%s\n\n' "$psaux_mem"
	
	echo "Going back to monitoring menu..."
	printf '\n'
	sleep 1
	monitoring_menu

}
