#!/usr/bin/env bash

source ../main

user_menu_actions() {
	print_user
	while true; do
		read -p "Please choose : " uchoice
		case "$uchoice" in
			1) user_create ;;
			2) user_info_get ;;
			3) user_delete ;;
			4) user_add_group ;;
			#3) multiple_user_create ;;
			#3) multiple_user_add_group ;;
			q) main_menu ;;
		esac
	done
}

print_user(){
	local userMenuOptions=(createUser getUserInfo deleteUser addUserToGroup addMultipleUsersToGroup removeUserFromGroup passwordPolicy 'Main menu (q)')
	local i=1
	for item in "${userMenuOptions[@]}"; do
		echo "${i}: ${item}"
		(( i++ ))
	done
	printf '\n'
}

user_create(){
	local userName
	local userPass
	local confPass

	read -p "Please enter a username: " userName
	read -s -p "Please enter a password: " userPass
	printf '\n'
	read -s -p "Please confirm the password: " confPass
	
	if [[ $userPass == $confPass ]]; then
		echo "Provided passwords match! Creating user $userName"
		useradd -s /bin/bash -m $userName && echo "$userName:$userPass" | chpasswd && echo "Created User $userName with a home dir and /bin/bash as a Shell!"
		exit 0
	fi
}


multiple_user_create(){
	local filepath
	local defaultPass
	local confDefaultPass
	local currentUsers=()
	local usersToAdd=()	

	echo "This option enables you to bulk create multiple users with a default password and add them to a secondary group!"
	echo "NOTE: The file format you provide must be a list of usernames one per line with no whitespaces"
	read -r "Please provide username list file absolute path: " filepath
	
	sleep 1
	
	echo "Here are the users, any that exist on the system will be skipped!"

	while read -r line; do
		echo "${line}"
	done
	
	while IFS=: read -r existingName _; do
		currentUsers+=("$existingName")
        done < /etc/passwd
	
}



user_info_get() {
	local activeUsers="$(cat /etc/passwd | grep /bin/bash | cut -d : -f 1)"
	for user in $activeUsers; do
		if [[ $user == "root" ]]; then
			continue
		fi
		printf '\n'
		printf 'Username: %s\n' "$user"
		printf 'UID: %s\n' "$(cat /etc/passwd | grep $user | cut -d : -f 3)"
		printf 'GID: %s\n' "$(cat /etc/passwd | grep $user | cut -d : -f 4)"
		printf 'Shell: %s\n' "$(cat /etc/passwd | grep $user | rev | cut -d : -f 1 | rev)"
		printf '\n'
	done
}

user_delete(){
	local userToDelete
	read -p "Please enter a username to delete: " userToDelete
	if [[ $userToDelete == "$(whoami)" ]]; then
		echo "Cannot delete yoursef..."
		printf '\n'
		exit 0
	elif [[ $userToDelete == "root" ]]; then
		echo "Cannot delete root..."
		printf '\n'
		exit 0
	else
		userdel -r $userToDelete
	fi
}

user_add_group(){
	
	local userName
	local groupToAdd
	local groupMembers
	local -a possibleGroups=()
	
	while IFS=: read -r groupName _; do
        	possibleGroups+=("$groupName")
    	done < /etc/group	

	local groupPresent
	groupPresent=0

	read -p "Please provide a username: " userName
	read -p "Please provide a group to add "$userName" to: " groupToAdd
	
	for group in "${possibleGroups[@]}"; do
		if [[ "$group" == "$groupToAdd" ]]; then
			((groupPresent++))
			echo "Group is present on system."
			printf '\n'
			break
		fi
		done
	
	if (( "$groupPresent" == 0 )); then
		echo "Group is not present..."
		echo "Going back to user menu."
		sleep 1
		printf '\n'
		user_menu_actions
	fi

	groupMembers="$(cat /etc/group | grep -w "$groupToAdd" | rev | cut -d : -f 1 | rev)"
	
	(
	IFS=',' read -r -a arr <<< "$groupMembers"
	
	for member in "${arr[@]}"; do
		if [[ "$member" == "$userName" ]]; then
			echo "$userName is already a member"
			echo "Going back to user menu"
			user_menu_actions
		fi
	done

	echo "Getting $groupToAdd members..."
	sleep 1
	printf '\n'

	for member in "${arr[@]}"; do
		echo "$member"
		printf '\n'
	done

	echo "Adding $userName to $groupToAdd"
	adduser $userName $groupToAdd && echo "User successfully added!" || echo "Error! Could not add User to $groupToAdd successfully..." && exit 1
	)
}
